name: Weekly Security Newsletter

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate newsletter
        run: node generate-newsletter.js
      - name: Commit newsletter
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: generate weekly security newsletter'
          file_pattern: 'newsletters/*.md'
